"""rieltor table init

Revision ID: 1cf15113bce1
Revises: a342f0ccb33e
Create Date: 2025-03-22 23:13:38.079346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf15113bce1'
down_revision: Union[str, None] = 'a342f0ccb33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flats_from_rieltor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_per_m2', sa.Integer(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('date_of_scrap', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Flats_from_rieltor')
    # ### end Alembic commands ###
