"""First migration

Revision ID: 2ca0f6d25fd0
Revises: 87f70f8c44a1
Create Date: 2025-03-16 20:56:41.703781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca0f6d25fd0'
down_revision: Union[str, None] = '87f70f8c44a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_per_sqm', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('rooms', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('square', sa.Integer(), nullable=False),
    sa.Column('room_squares', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Flats')
    # ### end Alembic commands ###
