"""empty message

Revision ID: 7eb0df44db45
Revises: c6a50ee8da8b
Create Date: 2025-05-12 19:02:43.040389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eb0df44db45'
down_revision: Union[str, None] = 'c6a50ee8da8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apartments_id', table_name='apartments')
    op.drop_table('apartments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_floors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('living_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('kitchen_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('year_built', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('building_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('has_balcony', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_furnished', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('listed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='apartments_seller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='apartments_pkey')
    )
    op.create_index('ix_apartments_id', 'apartments', ['id'], unique=False)
    # ### end Alembic commands ###
