"""Update migration

Revision ID: 9e5472691ad3
Revises: eda1576f86a4
Create Date: 2025-03-16 23:43:18.469499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5472691ad3'
down_revision: Union[str, None] = 'eda1576f86a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flats', sa.Column('year', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'Flats', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Flats', type_='unique')
    op.drop_column('Flats', 'year')
    # ### end Alembic commands ###
