"""update migration

Revision ID: a342f0ccb33e
Revises: 30a765c152f9
Create Date: 2025-03-20 14:59:48.324897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a342f0ccb33e'
down_revision: Union[str, None] = '30a765c152f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flats', sa.Column('date_of_scrap', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Flats', 'date_of_scrap')
    # ### end Alembic commands ###
