"""empty message

Revision ID: c9b9816e2d5c
Revises: 7ef49b838e79
Create Date: 2025-05-08 00:47:41.709113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b9816e2d5c'
down_revision: Union[str, None] = '7ef49b838e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('price_per_sqm', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('rooms', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('square', sa.Integer(), nullable=False),
    sa.Column('room_squares', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('date_of_scrap', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Flats_from_rieltor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_per_m2', sa.Integer(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('date_of_scrap', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('banned_ip',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('date_of_ban', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('expired_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rieltors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_of_registration', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('date_of_registration', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscription')
    op.drop_table('users')
    op.drop_table('subscription')
    op.drop_table('rieltors')
    op.drop_table('expired_tokens')
    op.drop_table('banned_ip')
    op.drop_table('Flats_from_rieltor')
    op.drop_table('Flats')
    # ### end Alembic commands ###
