"""Update migration

Revision ID: eda1576f86a4
Revises: 2ca0f6d25fd0
Create Date: 2025-03-16 23:41:58.873615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda1576f86a4'
down_revision: Union[str, None] = '2ca0f6d25fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flats', sa.Column('year', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'Flats', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Flats', type_='unique')
    op.drop_column('Flats', 'year')
    # ### end Alembic commands ###
