"""empty message

Revision ID: f831223619db
Revises: cf262ae4e966
Create Date: 2025-05-12 18:55:55.737340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f831223619db'
down_revision: Union[str, None] = 'cf262ae4e966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_apartments_id', table_name='apartments')
    op.create_unique_constraint(None, 'apartments', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartments', type_='unique')
    op.create_index('ix_apartments_id', 'apartments', ['id'], unique=False)
    op.alter_column('apartments', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
